import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useLayoutEffect, useRef } from 'react';
import styles from '../styles/Home.module.css';
import { gsap } from 'gsap';

const useIsomorphicLayoutEffect =
  typeof window !== 'undefined' ? useLayoutEffect : useEffect;

export default function Home() {
  const vercelRef = useRef(null);
  // gsap.to
  // useIsomorphicLayoutEffect(() => {
  //   gsap.to(vercelRef.current, {
  //     scale: 2,
  //     duration: 1,
  //   });
  // });

  // gsap.from
  // useIsomorphicLayoutEffect(() => {
  //   gsap.from(vercelRef.current, {
  //     scale: 5,
  //     duration: 1,
  //   });
  // });

  // gsap.fromTo
  useIsomorphicLayoutEffect(() => {
    gsap.fromTo(
      vercelRef.current,
      {
        opacity: 0,
      },
      {
        opacity: 1,
        scale: 3,
        duration: 2,
      }
    );
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <span ref={vercelRef} className={styles.logo}>
          <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
        </span>
      </main>
    </div>
  );
}
